name: Flutter test
on:
  workflow_dispatch:
  push:
    branches: ["Main"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.2"
          channel: "stable"
          cache: true
      - name: Get dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: run flutter tests
        run: |
          if [ -d "test" ]; then
            flutter test
          else
            echo "No test directory found, skipping tests."
          fi